# Generated by Django 4.2.7 on 2023-11-21 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0002_contact_us_rename_main_home_rename_serive_service_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
        migrations.RemoveField(
            model_name='contact_us',
            name='image',
        ),
    ]
